mq:
  cycle:
    queue: cycle-queue
    exchange: exchange-cycle
    routing-key: cycle.key
  event:
    queue: event-queue
    exchange: exchange-event
    routing-key: event.key
custom:
  deploy:
    domain: "http://localhost:3000"
    cycle: "http://localhost:3000"
spring:
  datasource:
    url: jdbc:mysql://pickcar-mysql:3306/pickcar
    username: pickcar
    password: pickcar
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true          # TODO: 추후 log 환경으로 변경
        format_sql: true
        use_sql_comments: true