spring:
  application:
    name: pickcar-emulator
  profiles:
    active: local

mq:
  cycle:
    exchange: exchange-cycle
    routing-key: cycle.key
    queue: cycle-queue-sse

logging:
  module-name: consumer
  sensitive-field-rules:
    - path: "none"
      fields: ["none"]