spring:
  application:
    name: pickcar-producer
  profiles:
    active: local

logging:
  moduleName: producer
  sensitiveFieldRules:
    - path: "none"
      fields: ["none"]

mq:
  cycle:
    exchange: exchange-cycle
    routing-key: cycle.key
    queue: cycle-queue-sse